# Generated by Django 6.0 on 2025-12-23 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsb', '0001_initial'),
        ('namespace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_name_per_user',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='unique_account_name_per_namespace'),
        ),
    ]
