# Generated by Django 6.0 on 2026-01-02 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsb', '0002_remove_account_unique_account_name_per_user_and_more'),
        ('namespace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_name_per_namespace',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
    ]
