# Generated by Django 6.0 on 2026-01-04 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsb', '0003_remove_account_unique_account_name_per_namespace_and_more'),
        ('namespace', '0002_alter_namespace_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_name_per_user',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='unique_account_name_per_namespace'),
        ),
    ]
