# Generated by Django 6.0 on 2026-01-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
    ]
