# Generated by Django 6.0 on 2026-01-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_destination_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
    ]
