# Generated by Django 6.0 on 2026-01-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_destination_currency_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
    ]
