# Generated by Django 6.0 on 2025-12-21 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('DZD', 'DZD')], max_length=3)),
                ('to_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('DZD', 'DZD')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'from_currency', 'to_currency'), name='unique_rate_per_user')],
            },
        ),
    ]
