# Generated by Django 6.0 on 2026-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namespace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
